### ISSUE TITLE
HOW TO USE THIS + THE EDITABE IMAGE DOSENT WORK FOR ME IT GIVES ERROR  Workspace.Stands.Extracting image data.Modules.BufferUtilities:194: invalid argument #1 to 'fromstring' (string expected, got nil)

### ISSUE THREAD

**Issue by devsoniexpert72** [Velover/fuzzy-search-package#1]

**Comment by Velover** [comment]
i review the place and fixed everything i could, idk what problems do you have with the BufferUtilities

**Comment by devsoniexpert72** [comment]
look bro im not tying to be annoying but can you please make a video version of the editable image?
